version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: ai-image-gen-minio
    ports:
      - "9000:9000"      # MinIO API
      - "9001:9001"      # MinIO Console (Web UI)
    environment:
      # Credentials for MinIO
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      # Enable console
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
    volumes:
      # Persist MinIO data
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - ai-image-gen-network

  # Optional: MinIO Client for bucket management
  minio-setup:
    image: minio/mc:latest
    container_name: ai-image-gen-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    environment:
      - MC_HOST_minio=http://minioadmin:minioadmin123@minio:9000
    entrypoint: >
      /bin/sh -c "
      mc alias set minio http://minio:9000 minioadmin minioadmin123;
      mc mb minio/ai-images || true;
      mc policy set public minio/ai-images || true;
      echo 'MinIO setup complete';
      exit 0;
      "
    networks:
      - ai-image-gen-network

volumes:
  minio_data:
    driver: local

networks:
  ai-image-gen-network:
    driver: bridge
